name: Back-end Workflow

on:
  push:
    branches: [back]
    paths:
      - 'back/**'
  pull_request:
    branches: [back]
    paths:
      - 'back/**'

jobs:
  test:
    name: Test and Coverage Hardhat
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: 'back/node_modules'
          key: ${{ runner.OS }}-node-${{ hashFiles('back/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npx hardhat test

      - name: Run Coverage
        run: npx hardhat coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: back/coverage/