name: Back-end Workflow

on:
  push:
    branches: [back]
    paths:
      - 'back/**'
  pull_request:
    branches: [back]
    paths:
      - 'back/**'

permissions:
  contents: read
  id-token: write

jobs:
  test:
    name: Test and Coverage Hardhat
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: 'back/node_modules'
          key: ${{ runner.OS }}-node-${{ hashFiles('back/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo ARBITRUM_SEPOLIA_RPC_URL=${{ secrets.ARBITRUM_SEPOLIA_RPC_URL }} >> .env
          echo PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} >> .env

      - name: Debug Environment Variables
        run: |
          if [ -n "$ARBITRUM_SEPOLIA_RPC_URL" ]; then
            echo "ARBITRUM_SEPOLIA_RPC_URL is set"
          else
            echo "ARBITRUM_SEPOLIA_RPC_URL is not set"
          fi
          if [ -n "$PRIVATE_KEY" ]; then
            echo "PRIVATE_KEY is set"
          else
            echo "PRIVATE_KEY is not set"
          fi
        env:
          ARBITRUM_SEPOLIA_RPC_URL: ${{ secrets.ARBITRUM_SEPOLIA_RPC_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Compile Contracts
        run: npx hardhat compile

      - name: Run Tests
        run: npx hardhat test

      - name: Run Coverage
        run: npx hardhat coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/