name: Back-end Test Suite

on:
  push:
    branches: [back]
    paths:
      - 'back/**'
  pull_request:
    branches: [back]
    paths:
      - 'back/**'

jobs:
  tests:
    name: Smart Contract Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js 20.11.1
        uses: actions/setup-node@v1
        with:
          node-version: 20.11.1

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: 'back/node_modules'
          key: back-node_modules-${{ hashFiles('back/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Compile Contracts
        run: npx hardhat compile

      - name: Run Tests
        run: npx hardhat test

      - name: Run Coverage
        run: npx hardhat coverage